intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

intf_libs += gtk4%lib{gtk4}
intf_libs += glib2%lib{glib-2.0}
intf_libs += appstream%lib{appstream}

lib{adwaita}: {h c}{** -{*-win32 *-macos} -**.gresources...} \
  $impl_libs $intf_libs

lib{adwaita}: {c}{adw-settings-impl-win32}: include = ($c.target.class == 'windows')
lib{adwaita}: {c}{adw-settings-impl-macos}: include = ($c.target.class == 'macos')

# Build options.
#
c.poptions =+ "-I$out_root" "-I$out_base" "-I$src_root" "-I$src_base" \
  "-DADWAITA_COMPILATION"

# Export options.
#
lib{adwaita}:
{
  c.export.poptions = "-I$out_root" "-I$out_base" "-I$src_root" "-I$src_base"
  c.export.libs = $intf_libs
  
  # Header (-I) and library (-L) search paths to use in the generated .pc
  # file instead of the default install.{include,lib}.
  #
  c.pkgconfig.include = include/ include/libadwaita/
}

if ($c.target.class != 'windows')
{
  c.libs += -lm
  lib{adwaita}: c.export.libs += -lm
}

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{adwaita}: bin.lib.version = "-$version.project_id"
else
  lib{adwaita}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libadwaita/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
h{*}:
{
  install         = include/libadwaita/
  install.subdirs = true
}

# Adwaita export a single public header file that in turn includes all the
# smaller header files into it.
#
# https://developer.gnome.org/documentation/guidelines/programming/coding-style.html
#
h{adwaita.h}@./:
{
  install = include/
}
